// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABxruQDs978xqNdFp-tefOb3N_kB-tsyg',
    appId: '1:746866701574:web:47d5eab9af31ddc5319a87',
    messagingSenderId: '746866701574',
    projectId: 'cspotify-app',
    authDomain: 'cspotify-app.firebaseapp.com',
    storageBucket: 'cspotify-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoEihOT4KlF06DrfhHNNP6-v2icbhpf-w',
    appId: '1:746866701574:android:01bb9a711925f185319a87',
    messagingSenderId: '746866701574',
    projectId: 'cspotify-app',
    storageBucket: 'cspotify-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWsoRCJm1ThsgKgTCT5xCP6fAp-O0XUwE',
    appId: '1:746866701574:ios:73e0527a07a43f32319a87',
    messagingSenderId: '746866701574',
    projectId: 'cspotify-app',
    storageBucket: 'cspotify-app.appspot.com',
    iosBundleId: 'com.example.cspotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWsoRCJm1ThsgKgTCT5xCP6fAp-O0XUwE',
    appId: '1:746866701574:ios:73e0527a07a43f32319a87',
    messagingSenderId: '746866701574',
    projectId: 'cspotify-app',
    storageBucket: 'cspotify-app.appspot.com',
    iosBundleId: 'com.example.cspotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABxruQDs978xqNdFp-tefOb3N_kB-tsyg',
    appId: '1:746866701574:web:b387b97a7d64c67f319a87',
    messagingSenderId: '746866701574',
    projectId: 'cspotify-app',
    authDomain: 'cspotify-app.firebaseapp.com',
    storageBucket: 'cspotify-app.appspot.com',
  );
}
